artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8b166ca6df9e4d19becaa17dcb65ec9e/artifacts
end_time: 1732470089270
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8b166ca6df9e4d19becaa17dcb65ec9e
run_name: marvelous-wasp-958
run_uuid: 8b166ca6df9e4d19becaa17dcb65ec9e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470068825
status: 3
tags: []
user_id: Miguel
