artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/05c62efabd5d4f3b8a70f2e39b892baa/artifacts
end_time: 1732470089663
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 05c62efabd5d4f3b8a70f2e39b892baa
run_name: GridSearch_CV_DecisionTree
run_uuid: 05c62efabd5d4f3b8a70f2e39b892baa
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470068825
status: 3
tags: []
user_id: Miguel
