artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d2c00ba642b3410cbc0e9d6c12fa78b7/artifacts
end_time: 1732464109728
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d2c00ba642b3410cbc0e9d6c12fa78b7
run_name: enchanting-ant-154
run_uuid: d2c00ba642b3410cbc0e9d6c12fa78b7
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464102165
status: 3
tags: []
user_id: Miguel
