artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/0660c7951aa84d61aff96903cfdd5aeb/artifacts
end_time: 1732491975894
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 0660c7951aa84d61aff96903cfdd5aeb
run_name: GridSearch_CV_GradientBoosting
run_uuid: 0660c7951aa84d61aff96903cfdd5aeb
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489719617
status: 3
tags: []
user_id: Miguel
