artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/94c8aa36041048a4a69ce3bba079dd4c/artifacts
end_time: 1732455378927
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 94c8aa36041048a4a69ce3bba079dd4c
run_name: GridSearch_CV_RandomForest
run_uuid: 94c8aa36041048a4a69ce3bba079dd4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455251805
status: 3
tags: []
user_id: Miguel
