artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d0cf40e1cb874d8997b3ce1af9b3e22d/artifacts
end_time: 1732478824405
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d0cf40e1cb874d8997b3ce1af9b3e22d
run_name: useful-cat-627
run_uuid: d0cf40e1cb874d8997b3ce1af9b3e22d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478812101
status: 3
tags: []
user_id: Miguel
