artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e10b6ae323f3400e9cb310ecc1af4e3b/artifacts
end_time: 1732522059938
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e10b6ae323f3400e9cb310ecc1af4e3b
run_name: bouncy-sponge-714
run_uuid: e10b6ae323f3400e9cb310ecc1af4e3b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522053490
status: 3
tags: []
user_id: Miguel
