artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/13752c98992d4f6aa0df9c67cf1fe650/artifacts
end_time: 1732476449442
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 13752c98992d4f6aa0df9c67cf1fe650
run_name: GridSearch_CV_LinearRegression
run_uuid: 13752c98992d4f6aa0df9c67cf1fe650
source_name: ''
source_type: 4
source_version: ''
start_time: 1732476439253
status: 4
tags: []
user_id: Miguel
