artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/66dcb139be004da2ae65b6b903c54dad/artifacts
end_time: 1732455251345
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 66dcb139be004da2ae65b6b903c54dad
run_name: flawless-hen-447
run_uuid: 66dcb139be004da2ae65b6b903c54dad
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455229274
status: 3
tags: []
user_id: Miguel
