artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ccf6c065a4204cf4a64fc26fe556c98d/artifacts
end_time: 1732478351658
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ccf6c065a4204cf4a64fc26fe556c98d
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: ccf6c065a4204cf4a64fc26fe556c98d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478327530
status: 3
tags: []
user_id: Miguel
