artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/cad926fba5da4b0e89b3d616ac5fca04/artifacts
end_time: 1732521644068
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: cad926fba5da4b0e89b3d616ac5fca04
run_name: stately-sow-946
run_uuid: cad926fba5da4b0e89b3d616ac5fca04
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521625077
status: 3
tags: []
user_id: Miguel
