artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f333dd792b33469ea6c462a6f8d3e82c/artifacts
end_time: 1732521918974
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f333dd792b33469ea6c462a6f8d3e82c
run_name: GridSearch_CV_RandomForest
run_uuid: f333dd792b33469ea6c462a6f8d3e82c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521797564
status: 3
tags: []
user_id: Miguel
