artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e498908c19ae47f3bea680bee899149f/artifacts
end_time: 1732521795814
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e498908c19ae47f3bea680bee899149f
run_name: Test evaluation - priceByArea - numerical - test_evaluation
run_uuid: e498908c19ae47f3bea680bee899149f
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521791873
status: 3
tags: []
user_id: Miguel
