artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f9a1151e82854e4c845c48f4aa678e88/artifacts
end_time: 1732523615415
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f9a1151e82854e4c845c48f4aa678e88
run_name: Test evaluation - priceByArea | non-linear - numerical -  - test_evaluation
run_uuid: f9a1151e82854e4c845c48f4aa678e88
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523607520
status: 3
tags: []
user_id: Miguel
