artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/23576cddcadf4c4a8fbe099e45f53e66/artifacts
end_time: 1732478326951
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 23576cddcadf4c4a8fbe099e45f53e66
run_name: popular-stoat-779
run_uuid: 23576cddcadf4c4a8fbe099e45f53e66
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478309363
status: 3
tags: []
user_id: Miguel
