artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a40b1aa0c7194cbaae807bc10ac19c82/artifacts
end_time: 1732479587647
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a40b1aa0c7194cbaae807bc10ac19c82
run_name: GridSearch_CV_DecisionTree
run_uuid: a40b1aa0c7194cbaae807bc10ac19c82
source_name: ''
source_type: 4
source_version: ''
start_time: 1732479557065
status: 3
tags: []
user_id: Miguel
