artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/510eadd2b6b940cfa4dbd61cabbd09cc/artifacts
end_time: 1732470904200
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 510eadd2b6b940cfa4dbd61cabbd09cc
run_name: delightful-snail-11
run_uuid: 510eadd2b6b940cfa4dbd61cabbd09cc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470513702
status: 3
tags: []
user_id: Miguel
