artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c21e3de948b34cef865c10aeba0d3ebe/artifacts
deleted_time: 1732455732242
end_time: 1732452058684
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: deleted
run_id: c21e3de948b34cef865c10aeba0d3ebe
run_name: loud-asp-798
run_uuid: c21e3de948b34cef865c10aeba0d3ebe
source_name: ''
source_type: 4
source_version: ''
start_time: 1732452047871
status: 3
tags: []
user_id: Miguel
