artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8f7e4cecbc9c48838b5daa13fbe44141/artifacts
end_time: 1732455378363
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8f7e4cecbc9c48838b5daa13fbe44141
run_name: rare-auk-382
run_uuid: 8f7e4cecbc9c48838b5daa13fbe44141
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455251805
status: 3
tags: []
user_id: Miguel
