artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a81e067d4eef4ae2b4b4b6afe15ad404/artifacts
end_time: 1732470494860
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a81e067d4eef4ae2b4b4b6afe15ad404
run_name: resilient-snake-356
run_uuid: a81e067d4eef4ae2b4b4b6afe15ad404
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470387066
status: 3
tags: []
user_id: Miguel
