artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/2b8adfa7c2a648ea8901e9efcd39a8fc/artifacts
end_time: 1732466549715
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 2b8adfa7c2a648ea8901e9efcd39a8fc
run_name: upset-sponge-568
run_uuid: 2b8adfa7c2a648ea8901e9efcd39a8fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732466541132
status: 3
tags: []
user_id: Miguel
