artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e59bd05122274f3bbdb1c0a73aa96d1d/artifacts
end_time: 1732491974636
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e59bd05122274f3bbdb1c0a73aa96d1d
run_name: gifted-stork-221
run_uuid: e59bd05122274f3bbdb1c0a73aa96d1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489719617
status: 3
tags: []
user_id: Miguel
