artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/034c5e3a47804f8c974bbcf3096ebf80/artifacts
end_time: 1732478491201
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 034c5e3a47804f8c974bbcf3096ebf80
run_name: GridSearch_CV_LassoRegression
run_uuid: 034c5e3a47804f8c974bbcf3096ebf80
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478472832
status: 3
tags: []
user_id: Miguel
