artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/207ac29d0c2040aca3f5aa49db1e337b/artifacts
end_time: 1732482111096
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 207ac29d0c2040aca3f5aa49db1e337b
run_name: treasured-asp-741
run_uuid: 207ac29d0c2040aca3f5aa49db1e337b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482001174
status: 3
tags: []
user_id: Miguel
