artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/12688a4f1d3b450e80cefe7b4a21f9a2/artifacts
end_time: 1732522067055
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 12688a4f1d3b450e80cefe7b4a21f9a2
run_name: GridSearch_CV_LassoRegression
run_uuid: 12688a4f1d3b450e80cefe7b4a21f9a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522060190
status: 3
tags: []
user_id: Miguel
