artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b2742bde193a4a94af51e85faf2aa1d7/artifacts
end_time: 1732463406825
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b2742bde193a4a94af51e85faf2aa1d7
run_name: capricious-cow-525
run_uuid: b2742bde193a4a94af51e85faf2aa1d7
source_name: ''
source_type: 4
source_version: ''
start_time: 1732463395057
status: 3
tags: []
user_id: Miguel
