artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/3d0cf21712d2472eb0f1cba74da1609e/artifacts
end_time: 1732477000619
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 3d0cf21712d2472eb0f1cba74da1609e
run_name: GridSearch_CV_LinearRegression
run_uuid: 3d0cf21712d2472eb0f1cba74da1609e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732476993585
status: 4
tags: []
user_id: Miguel
