artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bda24b8b67da4de9a08209e547b714db/artifacts
end_time: 1732521918661
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bda24b8b67da4de9a08209e547b714db
run_name: bemused-shrimp-549
run_uuid: bda24b8b67da4de9a08209e547b714db
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521797564
status: 3
tags: []
user_id: Miguel
