artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ec88d50ddaf9457fae341ecfaf392642/artifacts
end_time: 1732478202921
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ec88d50ddaf9457fae341ecfaf392642
run_name: GridSearch_CV_LinearRegression
run_uuid: ec88d50ddaf9457fae341ecfaf392642
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478185157
status: 3
tags: []
user_id: Miguel
