artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b68b491245004f9e9d84f2bc9e88cbbf/artifacts
end_time: 1732455201751
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b68b491245004f9e9d84f2bc9e88cbbf
run_name: GridSearch_CV_LinearRegression
run_uuid: b68b491245004f9e9d84f2bc9e88cbbf
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455186953
status: 3
tags: []
user_id: Miguel
