artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/6c43940d5ddf4ae8bd0c2cd98793eee9/artifacts
end_time: 1732464593761
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 6c43940d5ddf4ae8bd0c2cd98793eee9
run_name: GridSearch_CV_RandomForest
run_uuid: 6c43940d5ddf4ae8bd0c2cd98793eee9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464491763
status: 3
tags: []
user_id: Miguel
