artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/be160aa0f60a4b5d805de463cdb6ea28/artifacts
end_time: 1732524735015
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: be160aa0f60a4b5d805de463cdb6ea28
run_name: delicate-grouse-167
run_uuid: be160aa0f60a4b5d805de463cdb6ea28
source_name: ''
source_type: 4
source_version: ''
start_time: 1732524613033
status: 3
tags: []
user_id: Miguel
