artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/133f6c74f19a4a72846dcdd4cd2ecbd4/artifacts
end_time: 1732478308922
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 133f6c74f19a4a72846dcdd4cd2ecbd4
run_name: lyrical-hound-618
run_uuid: 133f6c74f19a4a72846dcdd4cd2ecbd4
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478291626
status: 3
tags: []
user_id: Miguel
