digest: dade50ce
name: dataset
profile: '{"num_rows": 41, "num_elements": 369}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "reciprocal_size", "required":
  true}, {"type": "long", "name": "distance", "required": true}, {"type": "long",
  "name": "bathrooms", "required": true}, {"type": "boolean", "name": "exterior",
  "required": true}, {"type": "boolean", "name": "parkingSpace_included_in_listing",
  "required": true}, {"type": "long", "name": "rooms", "required": true}, {"type":
  "string", "name": "floor_grouped", "required": true}, {"type": "string", "name":
  "p_area_property_grouped", "required": true}, {"type": "boolean", "name": "hasPlan",
  "required": true}]}'
source: '{"tags": {"mlflow.user": "Miguel", "mlflow.source.name": "c:\\Users\\Miguel\\.virtualenvs\\7._Rent_Madrid-EgbqKllV\\Lib\\site-packages\\ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
