artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/84ef4c8ad4c44f9eb06a74252ef949a9/artifacts
end_time: 1732522060114
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 84ef4c8ad4c44f9eb06a74252ef949a9
run_name: GridSearch_CV_LinearRegression
run_uuid: 84ef4c8ad4c44f9eb06a74252ef949a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522053490
status: 3
tags: []
user_id: Miguel
