artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/5873ed7ad45e4c4fb442f287ef6b7faa/artifacts
end_time: 1732478664630
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 5873ed7ad45e4c4fb442f287ef6b7faa
run_name: indecisive-shrew-200
run_uuid: 5873ed7ad45e4c4fb442f287ef6b7faa
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478651067
status: 3
tags: []
user_id: Miguel
