artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d882eab3c4e147a4b85c58968dfd81fc/artifacts
end_time: 1732522066686
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d882eab3c4e147a4b85c58968dfd81fc
run_name: receptive-fox-524
run_uuid: d882eab3c4e147a4b85c58968dfd81fc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522060190
status: 3
tags: []
user_id: Miguel
