artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/dedeb5cde5dc400886b29dacd6a3345f/artifacts
deleted_time: 1732455732195
end_time: 1732452067249
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: deleted
run_id: dedeb5cde5dc400886b29dacd6a3345f
run_name: upset-bat-617
run_uuid: dedeb5cde5dc400886b29dacd6a3345f
source_name: ''
source_type: 4
source_version: ''
start_time: 1732452059159
status: 3
tags: []
user_id: Miguel
