artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/3b00e6b39cac4d98a5a7a48896add60c/artifacts
end_time: 1732467555798
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 3b00e6b39cac4d98a5a7a48896add60c
run_name: GridSearch_CV_LassoRegression
run_uuid: 3b00e6b39cac4d98a5a7a48896add60c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732467547183
status: 3
tags: []
user_id: Miguel
