artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/4863b5ee0ece42beba4fce7194aa733d/artifacts
end_time: 1732466446896
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 4863b5ee0ece42beba4fce7194aa733d
run_name: whimsical-panda-499
run_uuid: 4863b5ee0ece42beba4fce7194aa733d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732466438807
status: 3
tags: []
user_id: Miguel
