artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/2ff09f4caa5b4554a763760e1ffac74e/artifacts
end_time: 1732522071668
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 2ff09f4caa5b4554a763760e1ffac74e
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 2ff09f4caa5b4554a763760e1ffac74e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522067206
status: 3
tags: []
user_id: Miguel
