artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9942b35a7b504257b38b31fcc9ce7eb5/artifacts
end_time: 1732523678136
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9942b35a7b504257b38b31fcc9ce7eb5
run_name: Test evaluation - priceByArea | linear - numerical & categorical - test_evaluation
run_uuid: 9942b35a7b504257b38b31fcc9ce7eb5
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523659020
status: 3
tags: []
user_id: Miguel
