artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/56fef1e5addf4a4b9ad6666ef79cf265/artifacts
end_time: 1732465555516
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 56fef1e5addf4a4b9ad6666ef79cf265
run_name: hilarious-colt-163
run_uuid: 56fef1e5addf4a4b9ad6666ef79cf265
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465547782
status: 3
tags: []
user_id: Miguel
