artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d420b2c72be04660b41c8a0bed3b4f0d/artifacts
end_time: 1732521644397
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d420b2c72be04660b41c8a0bed3b4f0d
run_name: GridSearch_CV_HuberRegressor
run_uuid: d420b2c72be04660b41c8a0bed3b4f0d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521625077
status: 3
tags: []
user_id: Miguel
