artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e9cc5ccbf0e042ddb884bb6b3c83d699/artifacts
end_time: 1732505098710
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e9cc5ccbf0e042ddb884bb6b3c83d699
run_name: nosy-calf-590
run_uuid: e9cc5ccbf0e042ddb884bb6b3c83d699
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505086553
status: 3
tags: []
user_id: Miguel
