artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a9e6f84ecb47422ba162fb4fd11ee636/artifacts
end_time: 1732523604509
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a9e6f84ecb47422ba162fb4fd11ee636
run_name: lyrical-shark-866
run_uuid: a9e6f84ecb47422ba162fb4fd11ee636
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522527475
status: 3
tags: []
user_id: Miguel
