artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1963b1a9dc224e94a989dded47ffd703/artifacts
end_time: 1732465315934
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1963b1a9dc224e94a989dded47ffd703
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 1963b1a9dc224e94a989dded47ffd703
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465309471
status: 3
tags: []
user_id: Miguel
