artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/25df886cce8745f09c264f31730e9676/artifacts
end_time: 1732464704891
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 25df886cce8745f09c264f31730e9676
run_name: Test evaluation - priceByArea | non-linear - numerical -  - test_evaluation
run_uuid: 25df886cce8745f09c264f31730e9676
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464699272
status: 3
tags: []
user_id: Miguel
