artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/eaec647bf6364419b1e3caf678a2720b/artifacts
end_time: 1732478811993
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: eaec647bf6364419b1e3caf678a2720b
run_name: GridSearch_CV_LinearRegression
run_uuid: eaec647bf6364419b1e3caf678a2720b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478799948
status: 3
tags: []
user_id: Miguel
