artifact_location: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/0
creation_time: 1732387146637
experiment_id: '0'
last_update_time: 1732387146637
lifecycle_stage: active
name: Default
