artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/32b14e3dba804bbb9b360ee74349df3f/artifacts
end_time: 1732505140135
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 32b14e3dba804bbb9b360ee74349df3f
run_name: handsome-goose-637
run_uuid: 32b14e3dba804bbb9b360ee74349df3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505125743
status: 3
tags: []
user_id: Miguel
