artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/184a1ffc79734ee6b871d449a9fce9aa/artifacts
end_time: 1732481907517
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 184a1ffc79734ee6b871d449a9fce9aa
run_name: capable-gnat-761
run_uuid: 184a1ffc79734ee6b871d449a9fce9aa
source_name: ''
source_type: 4
source_version: ''
start_time: 1732481886971
status: 3
tags: []
user_id: Miguel
