artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/dc194d7e3abf4a6e951f4bc3d00d8e52/artifacts
end_time: 1732465174990
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: dc194d7e3abf4a6e951f4bc3d00d8e52
run_name: rumbling-perch-721
run_uuid: dc194d7e3abf4a6e951f4bc3d00d8e52
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465167666
status: 3
tags: []
user_id: Miguel
