artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1bb8a23bddd54acf91d4db20252b3dbc/artifacts
end_time: 1732463406825
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1bb8a23bddd54acf91d4db20252b3dbc
run_name: awesome-dove-321
run_uuid: 1bb8a23bddd54acf91d4db20252b3dbc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732463395057
status: 3
tags: []
user_id: Miguel
