artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/96e2774a8ea642e38b0feb110f07b7d2/artifacts
end_time: 1732481919189
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 96e2774a8ea642e38b0feb110f07b7d2
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 96e2774a8ea642e38b0feb110f07b7d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1732481908044
status: 3
tags: []
user_id: Miguel
