artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/49aede28a6d241e7bef1b80c12292ba4/artifacts
end_time: 1732489140886
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 49aede28a6d241e7bef1b80c12292ba4
run_name: tasteful-dog-375
run_uuid: 49aede28a6d241e7bef1b80c12292ba4
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489121800
status: 3
tags: []
user_id: Miguel
