artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/fbf69959a74f44faba8ee5b529bc77b4/artifacts
end_time: 1732465180045
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: fbf69959a74f44faba8ee5b529bc77b4
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: fbf69959a74f44faba8ee5b529bc77b4
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465175474
status: 3
tags: []
user_id: Miguel
