artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bced7e54af3e4f2493ff5d880b002364/artifacts
end_time: 1732478824880
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bced7e54af3e4f2493ff5d880b002364
run_name: GridSearch_CV_LassoRegression
run_uuid: bced7e54af3e4f2493ff5d880b002364
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478812101
status: 3
tags: []
user_id: Miguel
