artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ac07b825619f42518dcec8dcb1e07eac/artifacts
end_time: 1732482138183
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ac07b825619f42518dcec8dcb1e07eac
run_name: worried-horse-597
run_uuid: ac07b825619f42518dcec8dcb1e07eac
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482111685
status: 3
tags: []
user_id: Miguel
