artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9ceab9cc83694f2babbe0a404afe4ae9/artifacts
end_time: 1732480729946
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9ceab9cc83694f2babbe0a404afe4ae9
run_name: able-auk-524
run_uuid: 9ceab9cc83694f2babbe0a404afe4ae9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732480598937
status: 3
tags: []
user_id: Miguel
