artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/46d5f768704847718fcf6fa01e6dd202/artifacts
end_time: 1732522052238
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 46d5f768704847718fcf6fa01e6dd202
run_name: Test evaluation - priceByArea | non-linear - numerical -  - test_evaluation
run_uuid: 46d5f768704847718fcf6fa01e6dd202
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522047771
status: 3
tags: []
user_id: Miguel
