artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8120acb3fdfd45c88e9b19213c0031fb/artifacts
end_time: 1732480757082
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8120acb3fdfd45c88e9b19213c0031fb
run_name: GridSearch_CV_DecisionTree
run_uuid: 8120acb3fdfd45c88e9b19213c0031fb
source_name: ''
source_type: 4
source_version: ''
start_time: 1732480730550
status: 3
tags: []
user_id: Miguel
