artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d25bdc6b6401419caeebfc2cede91a7b/artifacts
end_time: 1732464593426
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d25bdc6b6401419caeebfc2cede91a7b
run_name: learned-shrimp-678
run_uuid: d25bdc6b6401419caeebfc2cede91a7b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464491763
status: 3
tags: []
user_id: Miguel
