artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1fc159c236db4641a67e0ae388675aae/artifacts
end_time: 1732487534024
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1fc159c236db4641a67e0ae388675aae
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 1fc159c236db4641a67e0ae388675aae
source_name: ''
source_type: 4
source_version: ''
start_time: 1732487522161
status: 3
tags: []
user_id: Miguel
