artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c30cdcbdda6446df981f9993462ba90f/artifacts
end_time: 1732465296532
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c30cdcbdda6446df981f9993462ba90f
run_name: crawling-foal-774
run_uuid: c30cdcbdda6446df981f9993462ba90f
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465275329
status: 3
tags: []
user_id: Miguel
