artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d9eab5ed283e4c6b87a1f754bb0b8ff3/artifacts
end_time: 1732466557553
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d9eab5ed283e4c6b87a1f754bb0b8ff3
run_name: sedate-mule-531
run_uuid: d9eab5ed283e4c6b87a1f754bb0b8ff3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732466550008
status: 3
tags: []
user_id: Miguel
