artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/6fd02320ebd84881bbcda3029e0bd2dd/artifacts
end_time: 1732524031271
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 6fd02320ebd84881bbcda3029e0bd2dd
run_name: shivering-sloth-600
run_uuid: 6fd02320ebd84881bbcda3029e0bd2dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523999662
status: 3
tags: []
user_id: Miguel
