digest: 901aedd0
name: dataset
profile: '{"num_rows": 85, "num_elements": 425}'
schema: '{"mlflow_colspec": [{"type": "long", "name": "numPhotos", "required": true},
  {"type": "double", "name": "reciprocal_size", "required": true}, {"type": "long",
  "name": "distance", "required": true}, {"type": "long", "name": "bathrooms", "required":
  true}, {"type": "double", "name": "size", "required": true}]}'
source: '{"tags": {"mlflow.user": "Miguel", "mlflow.source.name": "c:\\Users\\Miguel\\.virtualenvs\\7._Rent_Madrid-EgbqKllV\\Lib\\site-packages\\ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
