artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e45f724c074545a28f4b71c9cedd3d4f/artifacts
end_time: 1732479556924
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e45f724c074545a28f4b71c9cedd3d4f
run_name: GridSearch_CV_RandomForest
run_uuid: e45f724c074545a28f4b71c9cedd3d4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1732479327849
status: 3
tags: []
user_id: Miguel
