artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/01cf148af3ab41fda8bfa963c6cf2230/artifacts
end_time: 1732464698385
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 01cf148af3ab41fda8bfa963c6cf2230
run_name: rogue-cow-941
run_uuid: 01cf148af3ab41fda8bfa963c6cf2230
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464605150
status: 3
tags: []
user_id: Miguel
