artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c69507aba1e64935a3cee9d4daefa92b/artifacts
end_time: 1732478220872
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c69507aba1e64935a3cee9d4daefa92b
run_name: GridSearch_CV_LassoRegression
run_uuid: c69507aba1e64935a3cee9d4daefa92b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478203047
status: 3
tags: []
user_id: Miguel
