artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/acaa0838a9c8437ca6985a30cea13afa/artifacts
end_time: 1732479587123
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: acaa0838a9c8437ca6985a30cea13afa
run_name: capricious-duck-372
run_uuid: acaa0838a9c8437ca6985a30cea13afa
source_name: ''
source_type: 4
source_version: ''
start_time: 1732479557065
status: 3
tags: []
user_id: Miguel
