artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/4ff9a04514df413aa28a7a8c8d27bec3/artifacts
end_time: 1732478413854
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 4ff9a04514df413aa28a7a8c8d27bec3
run_name: receptive-snipe-525
run_uuid: 4ff9a04514df413aa28a7a8c8d27bec3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478396388
status: 3
tags: []
user_id: Miguel
