artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/28a4c6ef26ee4cc2a67c89c4d055be17/artifacts
end_time: 1732478824405
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 28a4c6ef26ee4cc2a67c89c4d055be17
run_name: carefree-carp-602
run_uuid: 28a4c6ef26ee4cc2a67c89c4d055be17
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478812101
status: 3
tags: []
user_id: Miguel
