artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d80b2d89c79e45ce8eaeff3c7f2d5ac7/artifacts
end_time: 1732505110766
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d80b2d89c79e45ce8eaeff3c7f2d5ac7
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: d80b2d89c79e45ce8eaeff3c7f2d5ac7
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505099038
status: 3
tags: []
user_id: Miguel
