artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ce20664edbc547bdb1ab845147aee8bc/artifacts
end_time: 1732485411307
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ce20664edbc547bdb1ab845147aee8bc
run_name: dapper-gnat-410
run_uuid: ce20664edbc547bdb1ab845147aee8bc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482285482
status: 3
tags: []
user_id: Miguel
