digest: b1ea6f3a
name: dataset
profile: '{"num_rows": 247, "num_elements": 741}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "size", "required": true},
  {"type": "long", "name": "distance", "required": true}, {"type": "string", "name":
  "floor_grouped", "required": true}]}'
source: '{"tags": {"mlflow.user": "Miguel", "mlflow.source.name": "c:\\Users\\Miguel\\.virtualenvs\\7._Rent_Madrid-EgbqKllV\\Lib\\site-packages\\ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
