artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c2e7b5d4ad96474bb1d3c0deb4ee776e/artifacts
end_time: 1732455227848
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c2e7b5d4ad96474bb1d3c0deb4ee776e
run_name: dapper-crane-197
run_uuid: c2e7b5d4ad96474bb1d3c0deb4ee776e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455201991
status: 3
tags: []
user_id: Miguel
