artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d78a4d0e8f6e491fbbee1a8b43818bbe/artifacts
end_time: 1732476379726
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d78a4d0e8f6e491fbbee1a8b43818bbe
run_name: GridSearch_CV_LinearRegression
run_uuid: d78a4d0e8f6e491fbbee1a8b43818bbe
source_name: ''
source_type: 4
source_version: ''
start_time: 1732476369520
status: 4
tags: []
user_id: Miguel
