artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/2ee75ee76d9142a0ad635f569b4c76e1/artifacts
end_time: 1732491996386
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 2ee75ee76d9142a0ad635f569b4c76e1
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 2ee75ee76d9142a0ad635f569b4c76e1
source_name: ''
source_type: 4
source_version: ''
start_time: 1732491976241
status: 3
tags: []
user_id: Miguel
