artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8fefabab955a438ab211db54ffd1784d/artifacts
end_time: 1732465155096
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8fefabab955a438ab211db54ffd1784d
run_name: GridSearch_CV_LinearRegression
run_uuid: 8fefabab955a438ab211db54ffd1784d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465142936
status: 3
tags: []
user_id: Miguel
