artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1cd5fe0f365e407fbc55aa538b254ddb/artifacts
end_time: 1732478246282
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1cd5fe0f365e407fbc55aa538b254ddb
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 1cd5fe0f365e407fbc55aa538b254ddb
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478221003
status: 3
tags: []
user_id: Miguel
