artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/76fc908a7ef247deb26a7dda0131df72/artifacts
end_time: 1732505153602
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 76fc908a7ef247deb26a7dda0131df72
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 76fc908a7ef247deb26a7dda0131df72
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505140626
status: 3
tags: []
user_id: Miguel
