artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b527b7a038e246d9b3154ad92fa6fdfa/artifacts
end_time: 1732470089270
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b527b7a038e246d9b3154ad92fa6fdfa
run_name: gaudy-frog-362
run_uuid: b527b7a038e246d9b3154ad92fa6fdfa
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470068825
status: 3
tags: []
user_id: Miguel
