artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d62ed88e0a71400ab5eb1e62668195ea/artifacts
end_time: 1732504935284
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d62ed88e0a71400ab5eb1e62668195ea
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: d62ed88e0a71400ab5eb1e62668195ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1732504923726
status: 3
tags: []
user_id: Miguel
