artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f553a74ec2bb4bf89bcbe8a27fa663f5/artifacts
end_time: 1732521791092
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f553a74ec2bb4bf89bcbe8a27fa663f5
run_name: sassy-foal-688
run_uuid: f553a74ec2bb4bf89bcbe8a27fa663f5
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521777841
status: 3
tags: []
user_id: Miguel
