artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9df875dc8c304fbbaeb00cbc03dca007/artifacts
end_time: 1732480730443
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9df875dc8c304fbbaeb00cbc03dca007
run_name: GridSearch_CV_RandomForest
run_uuid: 9df875dc8c304fbbaeb00cbc03dca007
source_name: ''
source_type: 4
source_version: ''
start_time: 1732480598937
status: 3
tags: []
user_id: Miguel
