artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/4ff3e04f7ef3464ea6efa39bcfd5d862/artifacts
end_time: 1732455251644
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 4ff3e04f7ef3464ea6efa39bcfd5d862
run_name: GridSearch_CV_LassoRegression
run_uuid: 4ff3e04f7ef3464ea6efa39bcfd5d862
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455229274
status: 3
tags: []
user_id: Miguel
