artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a76e321a8ad24fb38cdb66bce885baf8/artifacts
end_time: 1732489141407
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a76e321a8ad24fb38cdb66bce885baf8
run_name: GridSearch_CV_LassoRegression
run_uuid: a76e321a8ad24fb38cdb66bce885baf8
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489121800
status: 3
tags: []
user_id: Miguel
