artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9cb2e4363b9b4ba98feda429cbff8c1b/artifacts
end_time: 1732480279884
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9cb2e4363b9b4ba98feda429cbff8c1b
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 9cb2e4363b9b4ba98feda429cbff8c1b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732480258584
status: 3
tags: []
user_id: Miguel
