artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c15c0e4e2c6342eaa2eed8ba882e7a4d/artifacts
end_time: 1732477051371
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c15c0e4e2c6342eaa2eed8ba882e7a4d
run_name: tasteful-rook-521
run_uuid: c15c0e4e2c6342eaa2eed8ba882e7a4d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732477033521
status: 3
tags: []
user_id: Miguel
