artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/5af1e5797bbe405c86edb17c0ff78cfc/artifacts
end_time: 1732464101651
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 5af1e5797bbe405c86edb17c0ff78cfc
run_name: puzzled-fox-87
run_uuid: 5af1e5797bbe405c86edb17c0ff78cfc
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464082543
status: 3
tags: []
user_id: Miguel
