artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/7e508c7a5a484fee878d2ffc0c02baed/artifacts
end_time: 1732505740786
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 7e508c7a5a484fee878d2ffc0c02baed
run_name: GridSearch_CV_GradientBoosting
run_uuid: 7e508c7a5a484fee878d2ffc0c02baed
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505735865
status: 4
tags: []
user_id: Miguel
