artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e1d2a88fea9f44e9be75e7b998bf4fae/artifacts
end_time: 1732478327429
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e1d2a88fea9f44e9be75e7b998bf4fae
run_name: GridSearch_CV_LassoRegression
run_uuid: e1d2a88fea9f44e9be75e7b998bf4fae
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478309363
status: 3
tags: []
user_id: Miguel
