artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c77019dabaaa4b008eaeefb55f5af8f7/artifacts
end_time: 1732505098919
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c77019dabaaa4b008eaeefb55f5af8f7
run_name: GridSearch_CV_GradientBoosting
run_uuid: c77019dabaaa4b008eaeefb55f5af8f7
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505086553
status: 3
tags: []
user_id: Miguel
