artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b978d4baafe846fd924be813e2cada88/artifacts
end_time: 1732467555412
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b978d4baafe846fd924be813e2cada88
run_name: enchanting-sow-437
run_uuid: b978d4baafe846fd924be813e2cada88
source_name: ''
source_type: 4
source_version: ''
start_time: 1732467547183
status: 3
tags: []
user_id: Miguel
