artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b3555ebde19b4611b1ade88a8fd43c48/artifacts
end_time: 1732523656731
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b3555ebde19b4611b1ade88a8fd43c48
run_name: caring-slug-795
run_uuid: b3555ebde19b4611b1ade88a8fd43c48
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523636652
status: 3
tags: []
user_id: Miguel
