artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1adab7f86c7c46b981d83fa5e9c2fab8/artifacts
end_time: 1732522526991
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1adab7f86c7c46b981d83fa5e9c2fab8
run_name: smiling-fawn-690
run_uuid: 1adab7f86c7c46b981d83fa5e9c2fab8
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522513847
status: 3
tags: []
user_id: Miguel
