artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/b6205f31328243749bbabaf12d4b8cb3/artifacts
end_time: 1732478309273
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: b6205f31328243749bbabaf12d4b8cb3
run_name: GridSearch_CV_LinearRegression
run_uuid: b6205f31328243749bbabaf12d4b8cb3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478291626
status: 3
tags: []
user_id: Miguel
