artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8fad7c148fa341f59ecd9ddadd9a9787/artifacts
end_time: 1732466562727
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8fad7c148fa341f59ecd9ddadd9a9787
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 8fad7c148fa341f59ecd9ddadd9a9787
source_name: ''
source_type: 4
source_version: ''
start_time: 1732466558242
status: 3
tags: []
user_id: Miguel
