artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bb368feb8f2e492e999ba2b4aae54aae/artifacts
end_time: 1732522047119
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bb368feb8f2e492e999ba2b4aae54aae
run_name: gregarious-flea-659
run_uuid: bb368feb8f2e492e999ba2b4aae54aae
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521934641
status: 3
tags: []
user_id: Miguel
