artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9107e4062f3b45f6accbcc8ad47e5f39/artifacts
end_time: 1732521918661
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9107e4062f3b45f6accbcc8ad47e5f39
run_name: handsome-bass-77
run_uuid: 9107e4062f3b45f6accbcc8ad47e5f39
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521797564
status: 3
tags: []
user_id: Miguel
