artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/cf812b3c96f043ecaade92d1e15dd513/artifacts
end_time: 1732485413567
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: cf812b3c96f043ecaade92d1e15dd513
run_name: GridSearch_CV_GradientBoosting
run_uuid: cf812b3c96f043ecaade92d1e15dd513
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482285482
status: 3
tags: []
user_id: Miguel
