artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/25a24a2ceb5e4090a747e5967981d55b/artifacts
end_time: 1732482150436
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 25a24a2ceb5e4090a747e5967981d55b
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 25a24a2ceb5e4090a747e5967981d55b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482138713
status: 3
tags: []
user_id: Miguel
