artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a44ff58bdb2b43bcae3b37d81e1d7816/artifacts
end_time: 1732523656731
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a44ff58bdb2b43bcae3b37d81e1d7816
run_name: honorable-tern-952
run_uuid: a44ff58bdb2b43bcae3b37d81e1d7816
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523636652
status: 3
tags: []
user_id: Miguel
