artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e2af0d3f8c3b4085be309d28406ed1e3/artifacts
end_time: 1732470068691
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e2af0d3f8c3b4085be309d28406ed1e3
run_name: GridSearch_CV_RandomForest
run_uuid: e2af0d3f8c3b4085be309d28406ed1e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732469939898
status: 3
tags: []
user_id: Miguel
