artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/5a6c33baddfd41dbbe1f0929c9a39d1b/artifacts
end_time: 1732466446896
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 5a6c33baddfd41dbbe1f0929c9a39d1b
run_name: fearless-lamb-543
run_uuid: 5a6c33baddfd41dbbe1f0929c9a39d1b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732466438807
status: 3
tags: []
user_id: Miguel
