artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/8c85eb2d2809460b8a5ea7ba44f5a8ba/artifacts
end_time: 1732465167103
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 8c85eb2d2809460b8a5ea7ba44f5a8ba
run_name: nebulous-smelt-875
run_uuid: 8c85eb2d2809460b8a5ea7ba44f5a8ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465155185
status: 3
tags: []
user_id: Miguel
