artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/16fddce2fbc0425e9c2208d49a28e3fd/artifacts
end_time: 1732478413854
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 16fddce2fbc0425e9c2208d49a28e3fd
run_name: polite-steed-408
run_uuid: 16fddce2fbc0425e9c2208d49a28e3fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478396388
status: 3
tags: []
user_id: Miguel
