artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/60c67bc3ed3e4af68409b7a55f103ff9/artifacts
end_time: 1732477051739
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 60c67bc3ed3e4af68409b7a55f103ff9
run_name: GridSearch_CV_LinearRegression
run_uuid: 60c67bc3ed3e4af68409b7a55f103ff9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732477033521
status: 3
tags: []
user_id: Miguel
