artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/89fe01bb314f4f5ca9ca3c7b1c6a60b2/artifacts
end_time: 1732524593965
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 89fe01bb314f4f5ca9ca3c7b1c6a60b2
run_name: fun-gull-595
run_uuid: 89fe01bb314f4f5ca9ca3c7b1c6a60b2
source_name: ''
source_type: 4
source_version: ''
start_time: 1732524031797
status: 3
tags: []
user_id: Miguel
