artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/7c28681a03794f4ea606ce4445b9d034/artifacts
end_time: 1732467561063
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 7c28681a03794f4ea606ce4445b9d034
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: 7c28681a03794f4ea606ce4445b9d034
source_name: ''
source_type: 4
source_version: ''
start_time: 1732467555892
status: 3
tags: []
user_id: Miguel
