artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/7a15961d282b4dd9a114b422b1e8fd9b/artifacts
end_time: 1732465275208
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 7a15961d282b4dd9a114b422b1e8fd9b
run_name: GridSearch_CV_LinearRegression
run_uuid: 7a15961d282b4dd9a114b422b1e8fd9b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465267343
status: 3
tags: []
user_id: Miguel
