artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/121bd2796fb84af688a5c26d8a2fed5e/artifacts
end_time: 1732470494860
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 121bd2796fb84af688a5c26d8a2fed5e
run_name: bouncy-owl-754
run_uuid: 121bd2796fb84af688a5c26d8a2fed5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470387066
status: 3
tags: []
user_id: Miguel
