artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/61f8353bdb354983aac9e9b613ded88e/artifacts
end_time: 1732481432390
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 61f8353bdb354983aac9e9b613ded88e
run_name: GridSearch_CV_GradientBoosting
run_uuid: 61f8353bdb354983aac9e9b613ded88e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732480757186
status: 3
tags: []
user_id: Miguel
