artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/42fb6fe06b8c476c9d4ceedfa624c934/artifacts
end_time: 1732478220437
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 42fb6fe06b8c476c9d4ceedfa624c934
run_name: calm-roo-416
run_uuid: 42fb6fe06b8c476c9d4ceedfa624c934
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478203047
status: 3
tags: []
user_id: Miguel
