artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/7eb0bda35c83426ca8f142731ac82aae/artifacts
end_time: 1732478664630
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 7eb0bda35c83426ca8f142731ac82aae
run_name: puzzled-calf-271
run_uuid: 7eb0bda35c83426ca8f142731ac82aae
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478651067
status: 3
tags: []
user_id: Miguel
