artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bacc8140fc904dfd9e0ff7599f3c5576/artifacts
end_time: 1732470068266
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bacc8140fc904dfd9e0ff7599f3c5576
run_name: youthful-eel-937
run_uuid: bacc8140fc904dfd9e0ff7599f3c5576
source_name: ''
source_type: 4
source_version: ''
start_time: 1732469939898
status: 3
tags: []
user_id: Miguel
