artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ad474c65acb04f098a0d0702d92f6299/artifacts
end_time: 1732464115582
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ad474c65acb04f098a0d0702d92f6299
run_name: Test evaluation - priceByArea - numerical - test_evaluation
run_uuid: ad474c65acb04f098a0d0702d92f6299
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464110838
status: 3
tags: []
user_id: Miguel
