artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/15f106dedce1430da32d99ed866f2fe3/artifacts
end_time: 1732465547030
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 15f106dedce1430da32d99ed866f2fe3
run_name: placid-cub-860
run_uuid: 15f106dedce1430da32d99ed866f2fe3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465532465
status: 3
tags: []
user_id: Miguel
