artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/c55a8e4a5e8e4dd780e1a6065a7a8bc3/artifacts
end_time: 1732464593426
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: c55a8e4a5e8e4dd780e1a6065a7a8bc3
run_name: serious-steed-97
run_uuid: c55a8e4a5e8e4dd780e1a6065a7a8bc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464491763
status: 3
tags: []
user_id: Miguel
