artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bbed8da719b046eca39139e871e474cd/artifacts
end_time: 1732523605355
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bbed8da719b046eca39139e871e474cd
run_name: GridSearch_CV_GradientBoosting
run_uuid: bbed8da719b046eca39139e871e474cd
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522527475
status: 3
tags: []
user_id: Miguel
