artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/2dfdd21c3fff4f458d5123148cdd800e/artifacts
end_time: 1732485440973
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 2dfdd21c3fff4f458d5123148cdd800e
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 2dfdd21c3fff4f458d5123148cdd800e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732485413807
status: 3
tags: []
user_id: Miguel
