artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ab7787cbce38495abe30dad69b74b45c/artifacts
end_time: 1732505836754
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ab7787cbce38495abe30dad69b74b45c
run_name: GridSearch_CV_GradientBoosting
run_uuid: ab7787cbce38495abe30dad69b74b45c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505810754
status: 3
tags: []
user_id: Miguel
