artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/0e2cbfebae16436389d87bfe8de3e20c/artifacts
end_time: 1732485411307
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 0e2cbfebae16436389d87bfe8de3e20c
run_name: silent-hound-703
run_uuid: 0e2cbfebae16436389d87bfe8de3e20c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482285482
status: 3
tags: []
user_id: Miguel
