artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/82ce1f2e2aac4e43bd655179768dcf37/artifacts
end_time: 1732476886946
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 82ce1f2e2aac4e43bd655179768dcf37
run_name: GridSearch_CV_LinearRegression
run_uuid: 82ce1f2e2aac4e43bd655179768dcf37
source_name: ''
source_type: 4
source_version: ''
start_time: 1732476879707
status: 4
tags: []
user_id: Miguel
