artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/6898cf26ffc54dcabce6e4528d08592a/artifacts
end_time: 1732482138183
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 6898cf26ffc54dcabce6e4528d08592a
run_name: thundering-stoat-467
run_uuid: 6898cf26ffc54dcabce6e4528d08592a
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482111685
status: 3
tags: []
user_id: Miguel
