artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f76a6e2adeb94c3fba9aa9be58919e73/artifacts
end_time: 1732521644068
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f76a6e2adeb94c3fba9aa9be58919e73
run_name: casual-shrimp-915
run_uuid: f76a6e2adeb94c3fba9aa9be58919e73
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521625077
status: 3
tags: []
user_id: Miguel
