artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/0d424faeb5ba47f1a2f92cfbfbbfaa14/artifacts
end_time: 1732521659412
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 0d424faeb5ba47f1a2f92cfbfbbfaa14
run_name: fortunate-carp-217
run_uuid: 0d424faeb5ba47f1a2f92cfbfbbfaa14
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521644544
status: 3
tags: []
user_id: Miguel
