artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/25cbcba3983d4dcd93b01a6975d1f3b9/artifacts
end_time: 1732523656731
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 25cbcba3983d4dcd93b01a6975d1f3b9
run_name: rumbling-hound-771
run_uuid: 25cbcba3983d4dcd93b01a6975d1f3b9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523636652
status: 3
tags: []
user_id: Miguel
