artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/af24e55bc2ef4af7bf930ad578d6fb76/artifacts
end_time: 1732478066939
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: af24e55bc2ef4af7bf930ad578d6fb76
run_name: glamorous-wolf-278
run_uuid: af24e55bc2ef4af7bf930ad578d6fb76
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478051749
status: 3
tags: []
user_id: Miguel
