artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/5ff1aa2b34dd43a0ac5141c5a44d2aac/artifacts
end_time: 1732522066686
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 5ff1aa2b34dd43a0ac5141c5a44d2aac
run_name: monumental-crow-69
run_uuid: 5ff1aa2b34dd43a0ac5141c5a44d2aac
source_name: ''
source_type: 4
source_version: ''
start_time: 1732522060190
status: 3
tags: []
user_id: Miguel
