artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/9ad9152e5bf94ac78c7e5f9ff36c09a3/artifacts
end_time: 1732491974636
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 9ad9152e5bf94ac78c7e5f9ff36c09a3
run_name: orderly-gnu-639
run_uuid: 9ad9152e5bf94ac78c7e5f9ff36c09a3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489719617
status: 3
tags: []
user_id: Miguel
