artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1b6ba4a33af942f8ba99895ecec843c1/artifacts
end_time: 1732521624519
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1b6ba4a33af942f8ba99895ecec843c1
run_name: nervous-steed-820
run_uuid: 1b6ba4a33af942f8ba99895ecec843c1
source_name: ''
source_type: 4
source_version: ''
start_time: 1732521604248
status: 3
tags: []
user_id: Miguel
