artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/18f10faedc8e4fe79d8963cef504f5eb/artifacts
end_time: 1732478051638
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 18f10faedc8e4fe79d8963cef504f5eb
run_name: GridSearch_CV_LinearRegression
run_uuid: 18f10faedc8e4fe79d8963cef504f5eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478030544
status: 3
tags: []
user_id: Miguel
