artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f49e693c3b93491a9ff7b8e43ab5319a/artifacts
end_time: 1732469857991
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f49e693c3b93491a9ff7b8e43ab5319a
run_name: GridSearch_CV_DecisionTree
run_uuid: f49e693c3b93491a9ff7b8e43ab5319a
source_name: ''
source_type: 4
source_version: ''
start_time: 1732469839675
status: 3
tags: []
user_id: Miguel
