artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ab62b0b89c8f49f1a85f0d7ad2e9fc00/artifacts
end_time: 1732469857585
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ab62b0b89c8f49f1a85f0d7ad2e9fc00
run_name: abundant-chimp-105
run_uuid: ab62b0b89c8f49f1a85f0d7ad2e9fc00
source_name: ''
source_type: 4
source_version: ''
start_time: 1732469839675
status: 3
tags: []
user_id: Miguel
