artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/5f6ca824270b44f582e35b3e64d8b152/artifacts
end_time: 1732470291562
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 5f6ca824270b44f582e35b3e64d8b152
run_name: Test evaluation - priceByArea | non-linear - numerical -  - test_evaluation
run_uuid: 5f6ca824270b44f582e35b3e64d8b152
source_name: ''
source_type: 4
source_version: ''
start_time: 1732470286049
status: 3
tags: []
user_id: Miguel
