artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/cb84e925c9a14cdd8ac0e5d11f5e199b/artifacts
end_time: 1732478090271
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: cb84e925c9a14cdd8ac0e5d11f5e199b
run_name: Test evaluation - priceByArea | linear - numerical - test_evaluation
run_uuid: cb84e925c9a14cdd8ac0e5d11f5e199b
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478067519
status: 3
tags: []
user_id: Miguel
