artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/13f52f64c6ab4afa896e3602cac89fa5/artifacts
end_time: 1732455227848
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 13f52f64c6ab4afa896e3602cac89fa5
run_name: bold-koi-234
run_uuid: 13f52f64c6ab4afa896e3602cac89fa5
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455201991
status: 3
tags: []
user_id: Miguel
