artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bf8cdd40da364c119017ef538c161be8/artifacts
end_time: 1732505140543
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bf8cdd40da364c119017ef538c161be8
run_name: GridSearch_CV_GradientBoosting
run_uuid: bf8cdd40da364c119017ef538c161be8
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505125743
status: 3
tags: []
user_id: Miguel
