artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/808e3cf2eda64c368099d2fe8b878d77/artifacts
end_time: 1732489154479
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 808e3cf2eda64c368099d2fe8b878d77
run_name: Test evaluation - priceByArea | linear - numerical & categorical - test_evaluation
run_uuid: 808e3cf2eda64c368099d2fe8b878d77
source_name: ''
source_type: 4
source_version: ''
start_time: 1732489141500
status: 3
tags: []
user_id: Miguel
