artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/e828a6d0dcd14b8f839f9c2af1dc5f99/artifacts
end_time: 1732481446164
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: e828a6d0dcd14b8f839f9c2af1dc5f99
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: e828a6d0dcd14b8f839f9c2af1dc5f99
source_name: ''
source_type: 4
source_version: ''
start_time: 1732481432556
status: 3
tags: []
user_id: Miguel
