artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/ad30c2c35dbe453cbc6e02e458b5bdc3/artifacts
end_time: 1732478395912
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: ad30c2c35dbe453cbc6e02e458b5bdc3
run_name: respected-hound-925
run_uuid: ad30c2c35dbe453cbc6e02e458b5bdc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478379001
status: 3
tags: []
user_id: Miguel
