artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a229bbe2a90445d2be19f9650cb23d50/artifacts
end_time: 1732523636549
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a229bbe2a90445d2be19f9650cb23d50
run_name: GridSearch_CV_LinearRegression
run_uuid: a229bbe2a90445d2be19f9650cb23d50
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523618849
status: 3
tags: []
user_id: Miguel
