artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/cd7fa44ca6c246c1b1621426b0f1f559/artifacts
end_time: 1732505878444
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: cd7fa44ca6c246c1b1621426b0f1f559
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: cd7fa44ca6c246c1b1621426b0f1f559
source_name: ''
source_type: 4
source_version: ''
start_time: 1732505836908
status: 3
tags: []
user_id: Miguel
