artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/09f2e81cafde4a56b1a5ed6dd6bb07ae/artifacts
end_time: 1732469839146
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 09f2e81cafde4a56b1a5ed6dd6bb07ae
run_name: amusing-turtle-314
run_uuid: 09f2e81cafde4a56b1a5ed6dd6bb07ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1732469720238
status: 3
tags: []
user_id: Miguel
