artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/0df4aadaa1cc4802bec87c6ef385f682/artifacts
end_time: 1732481886318
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 0df4aadaa1cc4802bec87c6ef385f682
run_name: mysterious-loon-927
run_uuid: 0df4aadaa1cc4802bec87c6ef385f682
source_name: ''
source_type: 4
source_version: ''
start_time: 1732481771033
status: 3
tags: []
user_id: Miguel
