artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/86dca812985d4afa9cde10575efb5a5d/artifacts
end_time: 1732478326951
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 86dca812985d4afa9cde10575efb5a5d
run_name: learned-fish-626
run_uuid: 86dca812985d4afa9cde10575efb5a5d
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478309363
status: 3
tags: []
user_id: Miguel
