artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/dcbeb28e049242e89f250dfe5bcf8b55/artifacts
end_time: 1732481907930
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: dcbeb28e049242e89f250dfe5bcf8b55
run_name: GridSearch_CV_DecisionTree
run_uuid: dcbeb28e049242e89f250dfe5bcf8b55
source_name: ''
source_type: 4
source_version: ''
start_time: 1732481886971
status: 3
tags: []
user_id: Miguel
