artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/72658c2da9e54e87ac6cb3e98834feac/artifacts
end_time: 1732464698385
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 72658c2da9e54e87ac6cb3e98834feac
run_name: worried-panda-855
run_uuid: 72658c2da9e54e87ac6cb3e98834feac
source_name: ''
source_type: 4
source_version: ''
start_time: 1732464605150
status: 3
tags: []
user_id: Miguel
