artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/bcc777bb58db48dca47235ed99f6ac52/artifacts
end_time: 1732525030109
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: bcc777bb58db48dca47235ed99f6ac52
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: bcc777bb58db48dca47235ed99f6ac52
source_name: ''
source_type: 4
source_version: ''
start_time: 1732525011060
status: 3
tags: []
user_id: Miguel
