artifact_location: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106
creation_time: 1732387146657
experiment_id: '327450721189704106'
last_update_time: 1732387146657
lifecycle_stage: active
name: rent_price_madrid
