artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/a23fbbc11eb647fc841be822f7d8ca1c/artifacts
end_time: 1732479556415
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: a23fbbc11eb647fc841be822f7d8ca1c
run_name: entertaining-cat-499
run_uuid: a23fbbc11eb647fc841be822f7d8ca1c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732479327849
status: 3
tags: []
user_id: Miguel
