artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/73b5f71fdb37435ea2a724eb7be539f9/artifacts
end_time: 1732465401053
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 73b5f71fdb37435ea2a724eb7be539f9
run_name: GridSearch_CV_LinearRegression
run_uuid: 73b5f71fdb37435ea2a724eb7be539f9
source_name: ''
source_type: 4
source_version: ''
start_time: 1732465398660
status: 4
tags: []
user_id: Miguel
