artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/1d4a1cff55234e16b2fc62af60b1a1d2/artifacts
end_time: 1732478326951
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 1d4a1cff55234e16b2fc62af60b1a1d2
run_name: luminous-fowl-532
run_uuid: 1d4a1cff55234e16b2fc62af60b1a1d2
source_name: ''
source_type: 4
source_version: ''
start_time: 1732478309363
status: 3
tags: []
user_id: Miguel
