artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/57e6caf0fbab4825b92ee2832c99c38e/artifacts
end_time: 1732524994738
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 57e6caf0fbab4825b92ee2832c99c38e
run_name: Test evaluation - price | non-linear - numerical & categorical - test_evaluation
run_uuid: 57e6caf0fbab4825b92ee2832c99c38e
source_name: ''
source_type: 4
source_version: ''
start_time: 1732524976996
status: 3
tags: []
user_id: Miguel
