artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/f76e7ec9598b49dd9e7f6bbc2ab73f63/artifacts
end_time: 1732455397042
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: f76e7ec9598b49dd9e7f6bbc2ab73f63
run_name: gentle-cat-204
run_uuid: f76e7ec9598b49dd9e7f6bbc2ab73f63
source_name: ''
source_type: 4
source_version: ''
start_time: 1732455379282
status: 3
tags: []
user_id: Miguel
