artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/d10d351aeb89410c9823b7cefa01a0a4/artifacts
end_time: 1732482138622
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: d10d351aeb89410c9823b7cefa01a0a4
run_name: GridSearch_CV_DecisionTree
run_uuid: d10d351aeb89410c9823b7cefa01a0a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1732482111685
status: 3
tags: []
user_id: Miguel
