artifact_uri: file:///c:/Users/Miguel/Desktop/Hackio/Proyectos/7. Rent Madrid/notebooks/../model_tracking/327450721189704106/92f7556d3a7e4aa2b7d64c2eab7f6a4c/artifacts
end_time: 1732523999126
entry_point_name: ''
experiment_id: '327450721189704106'
lifecycle_stage: active
run_id: 92f7556d3a7e4aa2b7d64c2eab7f6a4c
run_name: upbeat-perch-625
run_uuid: 92f7556d3a7e4aa2b7d64c2eab7f6a4c
source_name: ''
source_type: 4
source_version: ''
start_time: 1732523682845
status: 3
tags: []
user_id: Miguel
